package by.grsu.romanovskij.controller;

import by.grsu.romanovskij.DataTransferObject.UserRegistrationDto;
import by.grsu.romanovskij.model.User;
import by.grsu.romanovskij.service.RecaptchaService;
import by.grsu.romanovskij.service.UserService;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.stereotype.Service;
import org.springframework.ui.Model;
import org.springframework.util.StringUtils;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.util.HashMap;
import java.util.Map;

@Controller
@RequestMapping("/registration")
public class UserRegistrationController {
	private static final Logger logger = Logger.getLogger(UserRegistrationController.class);

	// Which is auto-generated by Spring, we will use it to handle the data1

	@Autowired
	private UserService userService;
	@Autowired
	private RecaptchaService recaptchaService;

	@ModelAttribute("user")
	public UserRegistrationDto userRegistrationDto() {
		return new UserRegistrationDto();
	}

	@GetMapping
	public String showRegistrationForm(Model model) {
		model.addAttribute("title", "Registration :: AirLine");
		return "registration";
	}

	@PostMapping
	public String registerUserAccount(Model model, @ModelAttribute("user") @Valid UserRegistrationDto userDto,
									  BindingResult result, @RequestParam(name="g-recaptcha-response") String recaptchaResponse,
									  HttpServletRequest request) {
		String ip = request.getRemoteAddr();
		String captchaVerifyMessage = recaptchaService.verifyRecaptcha(ip, recaptchaResponse);

		User existing = userService.findByUserEmail(userDto.getUserEmail());
		if (existing != null) {
			result.rejectValue("userEmail", "", "An account with this e-mail address is already registered");
		}

		if (result.hasErrors()) {
			return "registration";
		}

		if (!StringUtils.isEmpty(captchaVerifyMessage)) {
			Map<String, Object> response = new HashMap<>();
			model.addAttribute("error", "GoogleCaptcha says you're a robot!");
			response.put("message", captchaVerifyMessage);
			logger.error(response);
			return "registration";
		}

		userService.save(userDto);
		return "redirect:/registration?success";
	}

}
