package by.grsu.romanovskij.controller;

import by.grsu.romanovskij.DataTransferObject.UserRegistrationDto;
import by.grsu.romanovskij.model.User;
import by.grsu.romanovskij.service.UserService;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.validation.Valid;

@Controller
@RequestMapping("/registration")
public class UserRegistrationController {
	private static final Logger logger = Logger.getLogger(UserRegistrationController.class);

	// Which is auto-generated by Spring, we will use it to handle the data1

	@Autowired
	private UserService userService;

	@ModelAttribute("user")
	public UserRegistrationDto userRegistrationDto() {
		return new UserRegistrationDto();
	}

	@GetMapping
	public String showRegistrationForm(Model model) {
		model.addAttribute("title", "Registration :: AirLine");
		return "registration";
	}

	@PostMapping
	public String registerUserAccount(Model model, @ModelAttribute("user") @Valid UserRegistrationDto userDto,
									  BindingResult result) {

		User existing = userService.findByUserEmail(userDto.getUserEmail());
		if (existing != null) {
			result.rejectValue("userEmail", "", "An account with this e-mail address is already registered");
		}

		if (result.hasErrors()) {
			return "registration";
		}

		userService.save(userDto);
		return "redirect:/registration?success";
	}

}
